### ISSUE TITLE
JOSS review: testing issues

### ISSUE THREAD

**Issue by amcandio** [understanding-search/maze-dataset#74]
When running `make test` I'm facing the following issues:

### 1. Import errors:

Seems like `frozendict` and `pysr` were not included as part of project dependencies.
```
_____________________________________________________ ERROR collecting tests/unit/generation/test_solved_maze.py 
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/generation/test_solved_maze.py:5: in <module>
    from maze_dataset.testing_utils import LEGACY_AND_EQUIVALENT_TOKENIZERS
maze_dataset/testing_utils.py:9: in <module>
    import frozendict
E   ModuleNotFoundError: No module named 'frozendict'
```

```
Traceback (most recent call last):
  File ".../maze-dataset/notebooks/../tests/_temp/notebooks/estimate_dataset_fractions.py", line 15, in <module>
    import pysr  # noqa: F401
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'pysr'
```

### 2. Notebook errors taking too long

Not an issue per se but would be good for users to be able to run those tests separatedly and have `README.md` file explain how to.

### 3. rust_fst import errors

All tests seem to pass but I'm seeing this error at the end which is related to https://github.com/understanding-search/maze-dataset/issues/57. Test with this dependency should be able to be skipped.

```
    from rust_fst import Set as FstSet  # type: ignore[import-untyped]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'rust_fst'
```

After catching that import I see:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "maze-dataset/maze_dataset/tokenization/modular/fst.py", line 198, in <module>
    check_tokenizers_fst(
    ~~~~~~~~~~~~~~~~~~~~^
    	verbose=not args.quiet,
     ^^^^^^^^^^^^^^^^^^^^^^^
    	parallel=args.parallel,
     ^^^^^^^^^^^^^^^^^^^^^^^
    	n_check=n_check,
     ^^^^^^^^^^^^^^^^
    )
    ^
  File "maze-dataset/maze_dataset/tokenization/modular/fst.py", line 99, in check_tokenizers_fst
    get_tokenizers_fst()
    ~~~~~~~~~~~~~~~~~~^^
  File "maze-dataset/maze_dataset/tokenization/modular/fst_load.py", line 47, in get_tokenizers_fst
    return FstSet(MMT_FST_PATH.as_posix())
           ^^^^^^
NameError: name 'FstSet' is not defined
```

https://github.com/openjournals/joss-reviews/issues/8633

**Comment by mivanit** [comment]
this should now be resolved in #77
1. those have been added to dev dependencies
2. see commit [d57a3ee](https://github.com/understanding-search/maze-dataset/pull/77/commits/d57a3eef52225473394a32b3673993fefa0e2b6a)
3. tests using rust_fst will now just warn instead of error. I'm not sure if this is the correct behavior, might need to add a flag for this later. #57 will stay open to deal with this at some point, probably via migration to another FST library

**Comment by amcandio** [comment]
I'm still seeing this error after running the tests. You can probably reproduce this by uninstalling rust_fst and running `make test`

```
ModuleNotFoundError: No module named 'rust_fst'
make: *** [tokenizer-fst-check-small] Error 1
```

**Comment by mivanit** [comment]
Can you clarify which stage of the tests you are seeing the failure on?
`make test` is defined as:
```
.PHONY: test
test: clean test-unit test-notebooks-muutils tokenizer-fst-check-small
```
When uninstalling `rust_fst`, `test-unit` and `test-notebook-muutils` both pass, while `tokenizer-fst-check-small` fails.

I think that this is the correct behavior here -- unit tests and notebook tests pass, but the tokenizer fst checks fail. The latter tests are already separate, and getting them to pass without `rust_fst` would amount to the tests not doing anything.

I do, however, think that I should more clearly explain this behavior in the readme and documentation. Perhaps adding to the `# Development` section something like:

> Note: due to compatibility issues with the `rust_fst` package and Darwin/macOS systems, not all tests will pass on these systems. However, `make test-unit` and `make test-notebooks-muutils` should still pass. Please see #57 for updates on resolving this problem.

**Comment by mivanit** [comment]
added this in [9d60a03](https://github.com/understanding-search/maze-dataset/pull/77/commits/9d60a031656ac02970bc3f15fa510b4a1a7298f0), should be resolved now!

**Comment by amcandio** [comment]
Nice, all issues resolved here so closing!
